FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /workspace

COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline

COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app

RUN addgroup --system banquito && adduser --system --ingroup banquito banquito
COPY --from=build /workspace/target/core-admin-service-0.0.1-SNAPSHOT.jar /app/app.jar

ENV SPRING_PROFILES_ACTIVE=docker
ENV SERVER_PORT=8008

EXPOSE 8008 9093
USER banquito

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
