-- ============================================================================
-- BANCO BANQUITO V2 - CORE ADMIN SERVICE
-- Modelo fisico MySQL 8.4 LTS
-- Base: banquito_core_admin_db
-- Proposito: configuracion bancaria, sucursales, feriados, ventanas operativas,
-- catalogos de cuenta/transaccion, instituciones financieras y perfiles internos.
-- El tarifario de pagos masivos NO vive en Core; pertenece a Switch Facturacion.
-- ============================================================================
CREATE DATABASE IF NOT EXISTS banquito_core_admin_db
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE banquito_core_admin_db;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS OUTBOX_EVENT;
DROP TABLE IF EXISTS AUDITORIA_ADMIN_EVENTO;
DROP TABLE IF EXISTS USUARIO_CORE;
DROP TABLE IF EXISTS VENTANA_OPERATIVA;
DROP TABLE IF EXISTS SUBTIPO_TRANSACCION;
DROP TABLE IF EXISTS SUBTIPO_CUENTA;
DROP TABLE IF EXISTS INSTITUCION_FINANCIERA;
DROP TABLE IF EXISTS PARAMETRO_CORE;
DROP TABLE IF EXISTS FERIADO;
DROP TABLE IF EXISTS SUCURSAL;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE SUCURSAL (
  ID INT AUTO_INCREMENT NOT NULL,
  UUID_SUCURSAL CHAR(36) NOT NULL,
  CODIGO_SUCURSAL VARCHAR(10) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  CIUDAD VARCHAR(80) NOT NULL,
  DIRECCION VARCHAR(300) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID),
  CONSTRAINT UK_SUCURSAL_UUID UNIQUE (UUID_SUCURSAL),
  CONSTRAINT UK_SUCURSAL_CODIGO UNIQUE (CODIGO_SUCURSAL),
  CONSTRAINT CK_SUCURSAL_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Sucursales Banco BanQuito';

CREATE TABLE FERIADO (
  FECHA_FERIADO DATE NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  ES_FIN_SEMANA TINYINT(1) NOT NULL DEFAULT 0,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_FERIADO PRIMARY KEY (FECHA_FERIADO),
  CONSTRAINT CK_FERIADO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Calendario de dias no habiles';

CREATE TABLE PARAMETRO_CORE (
  CODIGO VARCHAR(60) NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  VALOR_TEXTO VARCHAR(300) NOT NULL,
  TIPO_DATO VARCHAR(20) NOT NULL DEFAULT 'STRING',
  DESCRIPCION VARCHAR(500) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_PARAMETRO_CORE PRIMARY KEY (CODIGO),
  CONSTRAINT CK_PARAM_CORE_TIPO CHECK (TIPO_DATO IN ('STRING','INTEGER','DECIMAL','BOOLEAN','TIME','JSON')),
  CONSTRAINT CK_PARAM_CORE_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Parametros funcionales del Core';

CREATE TABLE VENTANA_OPERATIVA (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(50) NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  DOMINIO_OPERATIVO VARCHAR(30) NOT NULL COMMENT 'CORE, SWITCH, CANAL, SFTP, CONTABLE',
  HORA_INICIO TIME NOT NULL,
  HORA_CORTE TIME NOT NULL,
  HORA_FIN TIME NOT NULL,
  DIAS_APLICA VARCHAR(50) NOT NULL DEFAULT 'LUN,MAR,MIE,JUE,VIE',
  TIMEZONE VARCHAR(60) NOT NULL DEFAULT 'America/Guayaquil',
  ACCION_DESPUES_CORTE VARCHAR(30) NOT NULL DEFAULT 'SIGUIENTE_DIA_HABIL',
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_VENTANA_OPERATIVA PRIMARY KEY (ID),
  CONSTRAINT UK_VENTANA_OPERATIVA_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_VENTANA_DOMINIO CHECK (DOMINIO_OPERATIVO IN ('CORE','SWITCH','CANAL','SFTP','CONTABLE')),
  CONSTRAINT CK_VENTANA_ACCION CHECK (ACCION_DESPUES_CORTE IN ('RECHAZAR','ENCOLAR','SIGUIENTE_DIA_HABIL','PERMITIR')),
  CONSTRAINT CK_VENTANA_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA')),
  CONSTRAINT CK_VENTANA_HORAS CHECK (HORA_INICIO <= HORA_CORTE AND HORA_CORTE <= HORA_FIN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Ventanas operativas y horarios de corte';

CREATE TABLE INSTITUCION_FINANCIERA (
  ID INT AUTO_INCREMENT NOT NULL,
  ROUTING_CODE VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(150) NOT NULL,
  ES_BANQUITO TINYINT(1) NOT NULL DEFAULT 0,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_INSTITUCION_FINANCIERA PRIMARY KEY (ID),
  CONSTRAINT UK_IF_ROUTING UNIQUE (ROUTING_CODE),
  CONSTRAINT CK_IF_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de instituciones financieras';

CREATE TABLE SUBTIPO_CUENTA (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(30) NOT NULL,
  TIPO_BASE VARCHAR(15) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(300) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_SUBTIPO_CUENTA PRIMARY KEY (ID),
  CONSTRAINT UK_SUBTIPO_CUENTA_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_SUBTIPO_CUENTA_BASE CHECK (TIPO_BASE IN ('AHORROS','CORRIENTE','NOMINA')),
  CONSTRAINT CK_SUBTIPO_CUENTA_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de productos de cuenta';

CREATE TABLE SUBTIPO_TRANSACCION (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(40) NOT NULL,
  NOMBRE VARCHAR(120) NOT NULL,
  TIPO_MOVIMIENTO_BASE VARCHAR(10) NOT NULL,
  DESCRIPCION VARCHAR(300) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_SUBTIPO_TRANSACCION PRIMARY KEY (ID),
  CONSTRAINT UK_SUBTIPO_TRANSACCION_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_SUBTIPO_TRANSACCION_BASE CHECK (TIPO_MOVIMIENTO_BASE IN ('DEBITO','CREDITO')),
  CONSTRAINT CK_SUBTIPO_TRANSACCION_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de subtipos de transaccion';

CREATE TABLE USUARIO_CORE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_USUARIO_CORE CHAR(36) NOT NULL,
  UUID_IDENTIDAD CHAR(36) NOT NULL COMMENT 'Referencia a identity-access-service; no password aqui',
  CODIGO_SUCURSAL VARCHAR(10) NULL COMMENT 'Sucursal operativa; sin FK cruzada hacia servicios consumidores',
  NOMBRE_COMPLETO VARCHAR(160) NOT NULL,
  CARGO VARCHAR(100) NULL,
  ESTADO_OPERATIVO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_USUARIO_CORE PRIMARY KEY (ID),
  CONSTRAINT UK_USUARIO_CORE_UUID UNIQUE (UUID_USUARIO_CORE),
  CONSTRAINT UK_USUARIO_CORE_IDENTIDAD UNIQUE (UUID_IDENTIDAD),
  CONSTRAINT CK_USUARIO_CORE_ESTADO CHECK (ESTADO_OPERATIVO IN ('ACTIVO','INACTIVO','SUSPENDIDO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Perfil operativo de empleados del banco';

CREATE TABLE AUDITORIA_ADMIN_EVENTO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  UUID_USUARIO CHAR(36) NULL,
  MODULO VARCHAR(60) NOT NULL,
  ACCION VARCHAR(80) NOT NULL,
  ENTIDAD VARCHAR(80) NOT NULL,
  ENTIDAD_ID VARCHAR(80) NULL,
  RESULTADO VARCHAR(15) NOT NULL,
  DETALLE_JSON JSON NULL,
  FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_AUDITORIA_ADMIN PRIMARY KEY (ID),
  CONSTRAINT CK_AUDITORIA_ADMIN_RESULTADO CHECK (RESULTADO IN ('OK','ERROR','DENEGADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auditoria local de admin-service';

CREATE TABLE OUTBOX_EVENT (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_EVENTO CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  AGREGADO_TIPO VARCHAR(80) NOT NULL,
  AGREGADO_ID VARCHAR(80) NOT NULL,
  PAYLOAD_JSON JSON NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  INTENTOS INT NOT NULL DEFAULT 0,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_PUBLICACION DATETIME NULL,
  ERROR_ULTIMO VARCHAR(1000) NULL,
  CONSTRAINT PK_OUTBOX_ADMIN PRIMARY KEY (ID),
  CONSTRAINT UK_OUTBOX_ADMIN_UUID UNIQUE (UUID_EVENTO),
  CONSTRAINT CK_OUTBOX_ADMIN_ESTADO CHECK (ESTADO IN ('PENDIENTE','PUBLICADO','ERROR','DESCARTADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Eventos confiables del admin-service';

CREATE INDEX IDX_USUARIO_CORE_IDENTIDAD ON USUARIO_CORE(UUID_IDENTIDAD);
CREATE INDEX IDX_VENTANA_DOMINIO ON VENTANA_OPERATIVA(DOMINIO_OPERATIVO, ESTADO);
CREATE INDEX IDX_OUTBOX_ADMIN_ESTADO ON OUTBOX_EVENT(ESTADO, FECHA_CREACION);

INSERT INTO SUCURSAL (UUID_SUCURSAL, CODIGO_SUCURSAL, NOMBRE, CIUDAD, DIRECCION) VALUES
(UUID(), '001', 'Sucursal Norte', 'Quito', 'Quito Norte'),
(UUID(), '002', 'Sucursal Sur', 'Quito', 'Quito Sur'),
(UUID(), '003', 'Sucursal Centro', 'Quito', 'Quito Centro'),
(UUID(), '004', 'Sucursal Valles', 'Quito', 'Cumbaya / Tumbaco'),
(UUID(), '999', 'Sucursal Digital', 'Quito', 'Canal Digital');

INSERT INTO PARAMETRO_CORE (CODIGO,NOMBRE,VALOR_TEXTO,TIPO_DATO,DESCRIPCION) VALUES
('IVA_PORCENTAJE','IVA vigente','15.00','DECIMAL','IVA vigente para servicios gravados'),
('BANQUITO_ROUTING_CODE','Routing Code BanQuito','BQTO001','STRING','Codigo de institucion financiera de BanQuito'),
('CORE_CURRENCY','Moneda funcional','USD','STRING','Moneda operativa del banco');

INSERT INTO VENTANA_OPERATIVA (CODIGO,NOMBRE,DOMINIO_OPERATIVO,HORA_INICIO,HORA_CORTE,HORA_FIN,DIAS_APLICA,ACCION_DESPUES_CORTE) VALUES
('CORE_CONTABLE','Ventana contable Core','CONTABLE','00:00:00','20:00:00','23:59:59','LUN,MAR,MIE,JUE,VIE','SIGUIENTE_DIA_HABIL'),
('SWITCH_INTERBANK','Ventana interbancaria Switch','SWITCH','08:00:00','18:00:00','23:59:59','LUN,MAR,MIE,JUE,VIE','ENCOLAR'),
('SFTP_PAGOS_MASIVOS','Carga SFTP pagos masivos','SFTP','00:00:00','18:00:00','23:59:59','LUN,MAR,MIE,JUE,VIE','ENCOLAR'),
('BANCA_WEB_EMPRESAS','Banca web empresas','CANAL','00:00:00','18:00:00','23:59:59','LUN,MAR,MIE,JUE,VIE','ENCOLAR'),
('VENTANILLA','Ventanilla sucursal','CANAL','08:30:00','17:00:00','17:00:00','LUN,MAR,MIE,JUE,VIE','RECHAZAR');

INSERT INTO INSTITUCION_FINANCIERA (ROUTING_CODE,NOMBRE,ES_BANQUITO) VALUES
('BQTO001','Banco BanQuito',1),
('PICH001','Banco Pichincha',0),
('PACF001','Banco del Pacifico',0),
('GYQL001','Banco Guayaquil',0);

INSERT INTO SUBTIPO_CUENTA (CODIGO,TIPO_BASE,NOMBRE,DESCRIPCION) VALUES
('AHO_STD','AHORROS','Cuenta de Ahorros Estandar','Producto base de ahorro'),
('COR_STD','CORRIENTE','Cuenta Corriente Estandar','Producto base corriente'),
('COR_NOM','NOMINA','Cuenta Corriente Nomina','Cuenta empresarial para nomina');

INSERT INTO SUBTIPO_TRANSACCION (CODIGO,NOMBRE,TIPO_MOVIMIENTO_BASE,DESCRIPCION) VALUES
('DEP_VENTANILLA','Deposito por Ventanilla','CREDITO','Deposito en efectivo'),
('RET_VENTANILLA','Retiro por Ventanilla','DEBITO','Retiro de efectivo'),
('TRF_P2P_DEB','Transferencia P2P Debito','DEBITO','Salida P2P'),
('TRF_P2P_CRE','Transferencia P2P Credito','CREDITO','Entrada P2P'),
('RESERVA_PM','Reserva Pago Masivo','DEBITO','Reserva/fondeo de lote de pagos masivos'),
('PAGO_ONUS','Pago masivo On-Us','CREDITO','Credito a beneficiario BanQuito'),
('CONSUMO_OFFUS','Consumo pago Off-Us','DEBITO','Consumo de reserva por pago interbancario'),
('COMISION_PM','Comision Pagos Masivos','DEBITO','Debito de comision calculada por Switch'),
('REVERSO','Reverso transaccional','CREDITO','Movimiento compensatorio');
