-- Evolución contractual Fase 1.2: elegibilidad de productos y subtipos compensatorios.
-- El procedimiento tolera un DDL parcialmente confirmado por MySQL.

DELIMITER $$

DROP PROCEDURE IF EXISTS align_account_product_eligibility$$
CREATE PROCEDURE align_account_product_eligibility()
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBTIPO_CUENTA'
           AND COLUMN_NAME = 'TIPOS_CLIENTE_PERMITIDOS'
    ) THEN
        ALTER TABLE SUBTIPO_CUENTA
            ADD COLUMN TIPOS_CLIENTE_PERMITIDOS VARCHAR(120) NOT NULL DEFAULT 'NATURAL,JURIDICO' AFTER DESCRIPCION;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBTIPO_CUENTA'
           AND COLUMN_NAME = 'PROPOSITOS_PERMITIDOS'
    ) THEN
        ALTER TABLE SUBTIPO_CUENTA
            ADD COLUMN PROPOSITOS_PERMITIDOS VARCHAR(180) NOT NULL DEFAULT 'GENERAL,OPERATIVA,NOMINA,IMPUESTOS' AFTER TIPOS_CLIENTE_PERMITIDOS;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBTIPO_CUENTA'
           AND COLUMN_NAME = 'SOPORTA_PAGOS_MASIVOS'
    ) THEN
        ALTER TABLE SUBTIPO_CUENTA
            ADD COLUMN SOPORTA_PAGOS_MASIVOS TINYINT(1) NOT NULL DEFAULT 0 AFTER PROPOSITOS_PERMITIDOS;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBTIPO_CUENTA'
           AND COLUMN_NAME = 'SOPORTA_CUENTA_FAVORITA'
    ) THEN
        ALTER TABLE SUBTIPO_CUENTA
            ADD COLUMN SOPORTA_CUENTA_FAVORITA TINYINT(1) NOT NULL DEFAULT 1 AFTER SOPORTA_PAGOS_MASIVOS;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBTIPO_CUENTA'
           AND COLUMN_NAME = 'SALDO_MINIMO_APERTURA'
    ) THEN
        ALTER TABLE SUBTIPO_CUENTA
            ADD COLUMN SALDO_MINIMO_APERTURA DECIMAL(19,2) NOT NULL DEFAULT 0.00 AFTER SOPORTA_CUENTA_FAVORITA;
    END IF;
END$$

CALL align_account_product_eligibility()$$
DROP PROCEDURE align_account_product_eligibility$$

DELIMITER ;

UPDATE SUBTIPO_CUENTA
   SET TIPOS_CLIENTE_PERMITIDOS = 'NATURAL,JURIDICO',
       PROPOSITOS_PERMITIDOS = 'GENERAL',
       SOPORTA_PAGOS_MASIVOS = 0,
       SOPORTA_CUENTA_FAVORITA = 1,
       SALDO_MINIMO_APERTURA = 0.00
 WHERE CODIGO = 'AHO_STD';

UPDATE SUBTIPO_CUENTA
   SET TIPOS_CLIENTE_PERMITIDOS = 'NATURAL,JURIDICO',
       PROPOSITOS_PERMITIDOS = 'GENERAL,OPERATIVA,IMPUESTOS',
       SOPORTA_PAGOS_MASIVOS = 1,
       SOPORTA_CUENTA_FAVORITA = 1,
       SALDO_MINIMO_APERTURA = 0.00
 WHERE CODIGO = 'COR_STD';

UPDATE SUBTIPO_CUENTA
   SET TIPOS_CLIENTE_PERMITIDOS = 'JURIDICO',
       PROPOSITOS_PERMITIDOS = 'NOMINA',
       SOPORTA_PAGOS_MASIVOS = 1,
       SOPORTA_CUENTA_FAVORITA = 1,
       SALDO_MINIMO_APERTURA = 0.00
 WHERE CODIGO = 'COR_NOM';

INSERT INTO SUBTIPO_TRANSACCION (CODIGO,NOMBRE,TIPO_MOVIMIENTO_BASE,DESCRIPCION,ESTADO)
VALUES
('REVERSO_DEBITO','Reverso débito','DEBITO','Movimiento débito que compensa una transacción crédito','ACTIVO'),
('REVERSO_CREDITO','Reverso crédito','CREDITO','Movimiento crédito que compensa una transacción débito','ACTIVO')
ON DUPLICATE KEY UPDATE
  NOMBRE = VALUES(NOMBRE),
  TIPO_MOVIMIENTO_BASE = VALUES(TIPO_MOVIMIENTO_BASE),
  DESCRIPCION = VALUES(DESCRIPCION),
  ESTADO = 'ACTIVO';

UPDATE SUBTIPO_TRANSACCION SET ESTADO = 'INACTIVO' WHERE CODIGO = 'REVERSO';
